name: Build & Publish

on:
  workflow_dispatch:
    inputs:
      os_version:
        default: ubuntu20.04
      cuda_version:
        default: 11.6.0
  push:
    branches:
      - master

env:
  # Use docker.io for Docker Hub if empty
  OS_VERSION: ${{ github.event.inputs.os_version }}
  CUDA_VERSION: ${{ github.event.inputs.cuda_version }}
  REGISTRY: ghcr.io
  SDK_IMAGE_NAME: ${{ github.repository_owner }}/cuda

jobs:
  build-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Setup environment
        run: |
          echo "OS_VERSION=${OS_VERSION:-ubuntu20.04}" >> $GITHUB_ENV
          echo "CUDA_VERSION=${CUDA_VERSION:-11.06}" >> $GITHUB_ENV

      - name: Print debug
        run: |
          echo "OS_VERSION: ${{ env.OS_VERSION }} | CUDA: ${{ env.CUDA_VERSION }}"

      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # # Install the cosign tool except on PR
      # # https://github.com/sigstore/cosign-installer
      # - name: Install cosign
      #   if: github.event_name != 'pull_request'
      #   uses: sigstore/cosign-installer@d6a3abf1bdea83574e28d40543793018b6035605
      #   with:
      #     cosign-release: "v1.7.1"

      # # https://github.com/docker/build-push-action/issues/579
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   with:
      #     version: v0.8.2

      # # Login against a Docker registry except on PR
      # # https://github.com/docker/login-action
      # - name: Log into registry ${{ env.REGISTRY }}
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # # Extract metadata (tags, labels) for Docker
      # # https://github.com/docker/metadata-action
      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.SDK_IMAGE_NAME }}

      # # Build and push Docker image with Buildx (don't push on PR)
      # # https://github.com/docker/build-push-action
      # - name: Build and push Docker image
      #   id: build-and-push
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     file: cuda/cuda-sdk.Dockerfile
      #     context: cuda
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: |
      #       ${{ steps.meta.outputs.tags }}
      #       ${{ env.REGISTRY }}/${{ env.SDK_IMAGE_NAME }}:${{ env.CUDA_VERSION }}-sdk
      #     labels: ${{ steps.meta.outputs.labels }}
      #     build-args: |
      #       OS_VERSION=${{ env.OS_VERSION }}
      #       CUDA_VERSION=${{ env.CUDA_VERSION }}

      ## Sign the resulting Docker image digest except on PRs.
      ## This will only write to the public Rekor transparency log when the Docker
      ## repository is public to avoid leaking data.  If you would like to publish
      ## transparency data even for private images, pass --force to cosign below.
      ## https://github.com/sigstore/cosign
      #- name: Sign the published Docker image
      #  if: ${{ github.event_name != 'pull_request' }}
      #  env:
      #    COSIGN_EXPERIMENTAL: "true"
      ## This step uses the identity token to provision an ephemeral certificate
      ## against the sigstore community Fulcio instance.
      #run: cosign sign ${{ env.REGISTRY }}/${{ env.SDK_IMAGE_NAME }}@${{ steps.build-and-push.outputs.imageid }}
